version: '3'
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
    volumes:
    - './src:/app/src'
    command: /bin/sh -c "yarn serve"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge