name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies (Node Modules)
      run: npm install
    - name: Execute lint (Rules to better code) via ESLint
      run: npm run lint
    - name: Execute build (To test Production stage)
      run: npm run build --if-present
